apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels: 
      app: mongodb
      tier: db
      project: roboshop
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:1.0.0
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      StorageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi

