apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels: 
      app: redis
      tier: db
      project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name:  redis
spec:
  clusterIP: None
  selector:
    app: redis
    tier: db
    project: roboshop
  ports:
  - name:  redis-port
    port:  6379
    protocol: TCP
    targetPort:  6379

